[package]
name = "properties-file-parser"
version = "0.1.4"
edition = "2021"
description = "This is a project for .properties file parsing (https://en.wikipedia.org/wiki/.properties)"
license = "MIT"

[dependencies]
anyhow = "1.0.91"
pest = "2.7.14"
pest_derive = "2.7.14"
thiserror = "2.0.3"